# =============================================================================
# Spurious regression in stationary time series: Monte Carlo evidence
#
# Companion script for the handout "Is Spurious Regression a Problem in
# Stationary Time Series?".  This file is the single computational source for
# every number, table and figure in the handout.
#
# Dependencies: R (>= 4.1), ggplot2, scales.  No other packages are required;
# all HAC covariance estimation is implemented here so that a single Bartlett
# estimator is used everywhere in the handout (see hac_lrv / hac_vcov below).
#
# Runtime: roughly 20-40 minutes single-threaded.  Set SPURIOUS_QUICK=1 in the
# environment for a fast (and correspondingly noisier) pass while drafting.
# =============================================================================

library(ggplot2)
library(scales)

# ---- global options ---------------------------------------------------------

quick <- nzchar(Sys.getenv("SPURIOUS_QUICK"))

Tmax        <- 5000
grid        <- seq(50, Tmax, by = 50)
selected_T  <- c(50, 200, 500, 1000, 2000, 5000)
alpha       <- 0.05

Nsim_main   <- if (quick)  200 else 2000   # main DGP grid
Nsim_vol    <- if (quick)  200 else 2000   # common stochastic volatility
Nsim_l2u    <- if (quick)  200 else 1000   # local-to-unity
Nsim_gr     <- if (quick)  200 else 1000   # Granger / distributed lag
Nsim_pow    <- if (quick)  200 else 2000   # local power

# Each experiment is seeded independently so that changing the replication
# count or the DGP list in one experiment does not silently change the results
# of any other.
seeds <- c(main = 2026, volatility = 20261, local_unity = 20262,
           granger = 20263, power = 20264)

# =============================================================================
# 1. Primitive helpers
# =============================================================================

# Draw a stationary AR(1) path.  The pre-sample state is drawn from the
# invariant distribution N(0, 1/(1 - phi^2)), so x[1] is already stationary and
# no burn-in is needed.
draw_ar1 <- function(n, phi) {
  as.vector(stats::filter(
    rnorm(n), phi, method = "recursive",
    init = rnorm(1, sd = 1 / sqrt(1 - phi^2))
  ))
}

# Draw an invertible MA(2) path: z_t = e_t + theta1 e_{t-1} + theta2 e_{t-2}.
# An MA process is stationary from the first observation, so the two leading
# NAs from the convolution filter are simply discarded.
draw_ma2 <- function(n, theta1, theta2) {
  e <- rnorm(n + 2)
  z <- stats::filter(e, c(1, theta1, theta2), method = "convolution", sides = 1)
  as.vector(z)[-(1:2)]
}

# Autocorrelations of the MA(2) above.
ma2_acf <- function(theta1, theta2, k) {
  den <- 1 + theta1^2 + theta2^2
  ifelse(k == 0, 1,
  ifelse(abs(k) == 1, (theta1 + theta1 * theta2) / den,
  ifelse(abs(k) == 2, theta2 / den, 0)))
}

# Bandwidth rule for the Bartlett kernel.  L ~ T^(1/3) is the MSE-optimal rate
# for the Bartlett kernel and satisfies L -> Inf, L/T -> 0.  It is deliberately
# more generous than the Newey-West rule of thumb 4 (T/100)^(2/9), because the
# scores generated by persistent AR(1) pairs have a long autocovariance tail.
hac_bandwidth <- function(n) floor(2 * n^(1 / 3))

# --- Bartlett long-run variance, scalar and matrix versions ------------------
# Both apply the same n/(n - k) degrees-of-freedom adjustment, where k is the
# number of estimated regression coefficients, so that every HAC number
# reported in the handout comes from one estimator.

hac_lrv <- function(score, L, dof_scale = 1) {
  n <- length(score)
  v <- sum(score^2) / n
  if (L > 0) {
    for (lag in seq_len(L)) {
      g <- sum(score[(lag + 1):n] * score[1:(n - lag)]) / n
      v <- v + 2 * (1 - lag / (L + 1)) * g
    }
  }
  v * dof_scale
}

hac_lrv_matrix <- function(S, L, dof_scale = 1) {
  n <- nrow(S)
  Omega <- crossprod(S) / n
  if (L > 0) {
    for (lag in seq_len(L)) {
      G <- crossprod(S[(lag + 1):n, , drop = FALSE],
                     S[1:(n - lag), , drop = FALSE]) / n
      Omega <- Omega + (1 - lag / (L + 1)) * (G + t(G))
    }
  }
  Omega * dof_scale
}

# Jarque-Bera normality statistic and its asymptotic chi-squared(2) p-value,
# implemented directly (rather than importing tseries) for the same reason the
# HAC estimator above is implemented directly: a single, auditable formula
# used everywhere in the handout.
jarque_bera <- function(x) {
  n    <- length(x)
  m    <- mean(x)
  v    <- mean((x - m)^2)
  skew <- mean((x - m)^3) / v^1.5
  kurt <- mean((x - m)^4) / v^2
  stat <- n / 6 * (skew^2 + (kurt - 3)^2 / 4)
  c(statistic = stat, p_value = 1 - pchisq(stat, df = 2))
}

# =============================================================================
# 2. Test statistics for the simple regression y ~ 1 + x
# =============================================================================

# Returns the conventional, HC0 and Bartlett-HAC t-ratios for the slope.
slope_t_stats <- function(x, y) {
  n  <- length(x)
  xc <- x - mean(x)
  yc <- y - mean(y)
  sxx <- sum(xc^2)
  b   <- sum(xc * yc) / sxx
  resid <- yc - b * xc
  score <- xc * resid

  dof <- n / (n - 2)
  se_conventional <- sqrt(sum(resid^2) / (n - 2) / sxx)
  se_hc0 <- sqrt(sum(score^2) * dof / sxx^2)
  se_hac <- sqrt(n * hac_lrv(score, hac_bandwidth(n), dof) / sxx^2)

  c(`Conventional OLS` = b / se_conventional,
    HC0 = b / se_hc0,
    HAC = b / se_hac)
}

# Rejection indicators at level alpha.  The conventional statistic is compared
# with the Student-t critical value it would have under exact Gaussian
# conditions; the robust statistics have N(0,1) limits, and the t critical
# value is used for them only as a mild finite-sample concession.  The
# difference is negligible at the sample sizes considered here.
slope_rejections <- function(x, y, alpha) {
  abs(slope_t_stats(x, y)) > qt(1 - alpha / 2, length(x) - 2)
}

# =============================================================================
# 3. DGP registry
#
# Each entry supplies a draw() returning a list(x, y) of length n, together
# with the theoretical variance ratio lambda implied by the theory section.
# Storing lambda per DGP (rather than deriving it from an AR(1) formula) lets
# the registry hold non-AR(1) designs.
# =============================================================================

ar_pair <- function(phi_x, phi_y) {
  force(phi_x); force(phi_y)
  function(n) list(x = draw_ar1(n, phi_x), y = draw_ar1(n, phi_y))
}

lambda_ar_pair <- function(phi_x, phi_y) {
  r <- phi_x * phi_y
  (1 + r) / (1 - r)
}

# --- the lambda = 1 design ---------------------------------------------------
# x is AR(1) with coefficient phi; y is an invertible MA(2).  Choosing
#     theta1 = -phi * theta2 / (1 + theta2)
# forces  sum_k rho_x(k) rho_y(k) = 1  exactly, so the conventional test is
# correctly sized even though BOTH series are visibly serially correlated.
# This is the counterexample to "serial correlation implies size distortion".
lambda1_phi    <- 0.5
lambda1_theta2 <- 0.5
lambda1_theta1 <- -lambda1_phi * lambda1_theta2 / (1 + lambda1_theta2)

lambda_ar_ma2 <- function(phi, theta1, theta2) {
  1 + 2 * sum(phi^(1:2) * ma2_acf(theta1, theta2, 1:2))
}

dgp_registry <- list(
  list(dgp = "iid", type = "stationary", lambda = 1,
       draw = function(n) list(x = rnorm(n), y = rnorm(n))),
  list(dgp = "(0.5,0.5)", type = "stationary", lambda = lambda_ar_pair(0.5, 0.5),
       draw = ar_pair(0.5, 0.5)),
  list(dgp = "(0.8,0.8)", type = "stationary", lambda = lambda_ar_pair(0.8, 0.8),
       draw = ar_pair(0.8, 0.8)),
  list(dgp = "(0.9,0.9)", type = "stationary", lambda = lambda_ar_pair(0.9, 0.9),
       draw = ar_pair(0.9, 0.9)),
  list(dgp = "(0.95,0.95)", type = "stationary", lambda = lambda_ar_pair(0.95, 0.95),
       draw = ar_pair(0.95, 0.95)),
  list(dgp = "(0.9,0.5)", type = "stationary", lambda = lambda_ar_pair(0.9, 0.5),
       draw = ar_pair(0.9, 0.5)),
  list(dgp = "(0.8,-0.8)", type = "stationary", lambda = lambda_ar_pair(0.8, -0.8),
       draw = ar_pair(0.8, -0.8)),
  list(dgp = "AR/MA lambda=1", type = "stationary",
       lambda = lambda_ar_ma2(lambda1_phi, lambda1_theta1, lambda1_theta2),
       draw = function(n) list(
         x = draw_ar1(n, lambda1_phi),
         y = draw_ma2(n, lambda1_theta1, lambda1_theta2))),
  list(dgp = "I(1)", type = "integrated", lambda = NA_real_,
       draw = function(n) list(x = cumsum(rnorm(n)), y = cumsum(rnorm(n))))
)

dgp_levels <- vapply(dgp_registry, `[[`, character(1), "dgp")

dgp_spec <- data.frame(
  dgp    = dgp_levels,
  type   = vapply(dgp_registry, `[[`, character(1), "type"),
  lambda = vapply(dgp_registry, `[[`, numeric(1), "lambda"),
  stringsAsFactors = FALSE
)
dgp_spec$asymptotic <- ifelse(
  is.na(dgp_spec$lambda), NA_real_,
  2 * pnorm(-qnorm(1 - alpha / 2) / sqrt(dgp_spec$lambda))
)

stationary_spec <- subset(dgp_spec, type == "stationary")

# =============================================================================
# 4. Main experiment
#
# One trajectory of length Tmax per replication.  The conventional statistic is
# evaluated on every nested prefix via cumulative sums; the HAC statistic, which
# cannot be updated recursively, is evaluated at selected_T only.
# =============================================================================

simulate_dgp <- function(entry, Tmax, grid, selected_T, Nsim, alpha) {
  conventional_rej <- matrix(FALSE, nrow = length(grid),       ncol = Nsim)
  hac_rej          <- matrix(FALSE, nrow = length(selected_T), ncol = Nsim)

  # t-statistics at selected_T only, kept purely for the Jarque-Bera check
  # below: the shape of the limiting distribution, as opposed to the
  # rejection frequencies above, which check its tail mass.
  conventional_t <- matrix(NA_real_, nrow = length(selected_T), ncol = Nsim)
  hac_t          <- matrix(NA_real_, nrow = length(selected_T), ncol = Nsim)
  sel_idx        <- match(selected_T, grid)

  for (r in seq_len(Nsim)) {
    d <- entry$draw(Tmax)
    x <- d$x
    y <- d$y

    # --- conventional statistic on every prefix, via running sums ----------
    cs <- cbind(cumsum(x), cumsum(y), cumsum(x^2), cumsum(y^2), cumsum(x * y))
    nn   <- grid
    Sx   <- cs[nn, 1]; Sy <- cs[nn, 2]
    Sxx  <- cs[nn, 3]; Syy <- cs[nn, 4]; Sxy <- cs[nn, 5]
    Sxxc <- Sxx - Sx^2 / nn
    Sxyc <- Sxy - Sx * Sy / nn
    Syyc <- Syy - Sy^2 / nn
    b    <- Sxyc / Sxxc
    ssr  <- Syyc - b * Sxyc
    se   <- sqrt((ssr / (nn - 2)) / Sxxc)
    tstat <- b / se
    conventional_rej[, r] <- abs(tstat) > qt(1 - alpha / 2, nn - 2)
    conventional_t[, r]   <- tstat[sel_idx]

    # --- HAC statistic at selected sample sizes ---------------------------
    for (j in seq_along(selected_T)) {
      n <- selected_T[j]
      stats <- slope_t_stats(x[seq_len(n)], y[seq_len(n)])
      hac_t[j, r]   <- stats[["HAC"]]
      hac_rej[j, r] <- abs(stats[["HAC"]]) > qt(1 - alpha / 2, n - 2)
    }
  }

  jb_conventional <- apply(conventional_t, 1, jarque_bera)
  jb_hac          <- apply(hac_t,          1, jarque_bera)

  list(
    conventional = data.frame(T = grid, reject = rowMeans(conventional_rej),
                              method = "Conventional OLS", dgp = entry$dgp,
                              Nsim = Nsim, stringsAsFactors = FALSE),
    hac = data.frame(T = selected_T, reject = rowMeans(hac_rej),
                     method = "HAC", dgp = entry$dgp,
                     Nsim = Nsim, stringsAsFactors = FALSE),
    normality = data.frame(
      T = rep(selected_T, 2),
      method = rep(c("Conventional OLS", "HAC"), each = length(selected_T)),
      jb_statistic = c(jb_conventional["statistic", ], jb_hac["statistic", ]),
      jb_pvalue    = c(jb_conventional["p_value", ],   jb_hac["p_value", ]),
      dgp = entry$dgp, Nsim = Nsim, stringsAsFactors = FALSE)
  )
}

set.seed(seeds[["main"]])
simulation_list <- lapply(dgp_registry, simulate_dgp,
                          Tmax = Tmax, grid = grid, selected_T = selected_T,
                          Nsim = Nsim_main, alpha = alpha)

res     <- do.call(rbind, lapply(simulation_list, `[[`, "conventional"))
hac_res <- do.call(rbind, lapply(simulation_list, `[[`, "hac"))
dgp_normality_res <- do.call(rbind, lapply(simulation_list, `[[`, "normality"))
res$dgp     <- factor(res$dgp,     levels = dgp_levels)
hac_res$dgp <- factor(hac_res$dgp, levels = dgp_levels)
dgp_normality_res$dgp <- factor(dgp_normality_res$dgp, levels = dgp_levels)

# Monte Carlo standard error of each reported proportion.
mcse <- function(p, N) sqrt(p * (1 - p) / N)
res$mcse     <- mcse(res$reject,     res$Nsim)
hac_res$mcse <- mcse(hac_res$reject, hac_res$Nsim)

comparison_table <- merge(
  subset(res, T %in% selected_T),
  dgp_spec[c("dgp", "lambda", "asymptotic")],
  by = "dgp"
)
comparison_table <- comparison_table[
  order(match(comparison_table$dgp, dgp_levels), comparison_table$T), ]

hac_comparison_table <- merge(
  subset(hac_res, dgp != "I(1)"),
  subset(res, T %in% selected_T & dgp != "I(1)"),
  by = c("dgp", "T"), suffixes = c("_hac", "_conventional")
)
hac_comparison_table <- hac_comparison_table[
  order(match(hac_comparison_table$dgp, dgp_levels), hac_comparison_table$T), ]

# =============================================================================
# 5. Extension 1: dependent series with a zero projection slope
#
# x and y share a persistent stochastic scale but have independent signs, so
# Cov(x, y) = 0 while the series are dependent.  The score is exactly serially
# uncorrelated, yet lambda = E(s^4) / E(s^2)^2 = exp(v_h) > 1: the distortion is
# entirely contemporaneous.  HC is sufficient here; HAC is valid but noisier.
# =============================================================================

simulate_common_volatility <- function(Tmax, selected_T, Nsim, alpha,
                                       volatility_rho = 0.95,
                                       volatility_variance = 0.5) {
  methods <- c("Conventional OLS", "HC0", "HAC")
  out <- array(FALSE, dim = c(length(selected_T), length(methods), Nsim),
               dimnames = list(NULL, methods, NULL))
  innovation_sd <- sqrt(volatility_variance * (1 - volatility_rho^2))

  for (r in seq_len(Nsim)) {
    h <- as.vector(stats::filter(
      rnorm(Tmax, sd = innovation_sd), volatility_rho,
      method = "recursive", init = rnorm(1, sd = sqrt(volatility_variance))
    ))
    s <- exp(h / 2)
    x <- s * rnorm(Tmax)
    y <- s * rnorm(Tmax)
    for (j in seq_along(selected_T)) {
      n <- selected_T[j]
      out[j, , r] <- slope_rejections(x[seq_len(n)], y[seq_len(n)], alpha)[methods]
    }
  }

  do.call(rbind, lapply(seq_along(selected_T), function(j) {
    data.frame(T = selected_T[j], method = methods,
               reject = as.numeric(rowMeans(out[j, , ])),
               Nsim = Nsim, dgp = "Common stochastic volatility",
               stringsAsFactors = FALSE)
  }))
}

common_volatility_variance <- 0.5
common_volatility_lambda   <- exp(common_volatility_variance)
common_volatility_asymptotic <- 2 * pnorm(
  -qnorm(1 - alpha / 2) / sqrt(common_volatility_lambda))

set.seed(seeds[["volatility"]])
common_volatility_res <- simulate_common_volatility(
  Tmax, selected_T, Nsim_vol, alpha,
  volatility_variance = common_volatility_variance)
common_volatility_res$mcse <- mcse(common_volatility_res$reject,
                                   common_volatility_res$Nsim)

# =============================================================================
# 6. Extension 2: local-to-unity triangular array
#
# phi_T = 1 - c/T, so the DGP changes with T.  Each finite-T process is
# stationary, but the sequence approaches the unit-root boundary.  Note that
# the pre-sample value is drawn from the invariant distribution, i.e. this is
# the STATIONARY-START local-to-unity design (the limit is an Ornstein-
# Uhlenbeck process begun in its stationary distribution).  A zero-start design
# gives materially different finite-sample rejection frequencies; the
# initialisation is a modelling choice, not a technicality.
# =============================================================================

simulate_local_to_unity <- function(selected_T, Nsim, alpha, c_local = 5) {
  methods <- c("Conventional OLS", "HAC")
  records <- vector("list", length(selected_T))
  for (j in seq_along(selected_T)) {
    n   <- selected_T[j]
    phi <- 1 - c_local / n
    rej <- matrix(FALSE, nrow = Nsim, ncol = length(methods),
                  dimnames = list(NULL, methods))
    for (r in seq_len(Nsim)) {
      rej[r, ] <- slope_rejections(draw_ar1(n, phi), draw_ar1(n, phi),
                                   alpha)[methods]
    }
    records[[j]] <- data.frame(T = n, phi = phi, method = methods,
                               reject = colMeans(rej), Nsim = Nsim,
                               dgp = "Local-to-unity",
                               stringsAsFactors = FALSE)
  }
  do.call(rbind, records)
}

local_to_unity_c <- 5
set.seed(seeds[["local_unity"]])
local_to_unity_res <- simulate_local_to_unity(selected_T, Nsim_l2u, alpha,
                                              c_local = local_to_unity_c)
local_to_unity_res$mcse <- mcse(local_to_unity_res$reject, local_to_unity_res$Nsim)

# =============================================================================
# 7. Extension 3: distributed lags, Granger causality, omitted dynamics
#
# x and y are generated INDEPENDENTLY, so the population projection coefficients
# on the x lags are exactly zero in BOTH specifications -- including the one
# that omits y_{t-1}.  There is therefore no omitted-variable bias anywhere in
# this experiment; the entire distortion in the misspecified column is a
# failure of the conventional covariance estimator, which is precisely why HAC
# repairs most of it.
# =============================================================================

# Joint Wald test.  Returns NA (rather than failing) if the covariance matrix
# is numerically singular, which can happen for HAC at the smallest sample
# sizes; such replications are dropped from the corresponding average.
wald_reject <- function(b, V, alpha) {
  V <- (V + t(V)) / 2
  stat <- tryCatch(as.numeric(crossprod(b, solve(V, b))),
                   error = function(e) NA_real_)
  if (!is.finite(stat) || stat < 0) return(NA)
  stat > qchisq(1 - alpha, df = length(b))
}

simulate_granger <- function(sample_sizes, Nsim, alpha, phi_x = 0.8, phi_y = 0.8) {
  designs <- c("Correct dynamic model", "Omit lagged y")
  methods <- c("Conventional OLS", "HAC")
  records <- vector("list", length(sample_sizes))

  for (j in seq_along(sample_sizes)) {
    n <- sample_sizes[j]
    rej <- array(NA, dim = c(Nsim, length(designs), length(methods)),
                 dimnames = list(NULL, designs, methods))
    L <- hac_bandwidth(n)

    for (r in seq_len(Nsim)) {
      x <- draw_ar1(n + 2, phi_x)
      y <- draw_ar1(n + 2, phi_y)
      yv    <- y[3:(n + 2)]
      ylag  <- y[2:(n + 1)]
      xlag1 <- x[2:(n + 1)]
      xlag2 <- x[1:n]

      X_correct <- cbind(1, ylag, xlag1, xlag2)
      X_omit    <- cbind(1, xlag1, xlag2)
      colnames(X_correct) <- c("const", "ylag", "xlag1", "xlag2")
      colnames(X_omit)    <- c("const", "xlag1", "xlag2")
      designs_X <- list(`Correct dynamic model` = X_correct,
                        `Omit lagged y`         = X_omit)

      for (design in designs) {
        X <- designs_X[[design]]
        k <- ncol(X)
        XtXinv <- tryCatch(chol2inv(chol(crossprod(X))), error = function(e) NULL)
        if (is.null(XtXinv)) next
        bhat  <- as.vector(XtXinv %*% crossprod(X, yv))
        resid <- as.vector(yv - X %*% bhat)
        idx   <- match(c("xlag1", "xlag2"), colnames(X))

        # conventional (homoskedastic) covariance
        s2 <- sum(resid^2) / (n - k)
        Vc <- s2 * XtXinv
        rej[r, design, "Conventional OLS"] <-
          wald_reject(bhat[idx], Vc[idx, idx, drop = FALSE], alpha)

        # Bartlett HAC covariance, same estimator as everywhere else
        S  <- X * resid
        Vh <- n * XtXinv %*% hac_lrv_matrix(S, L, n / (n - k)) %*% XtXinv
        rej[r, design, "HAC"] <-
          wald_reject(bhat[idx], Vh[idx, idx, drop = FALSE], alpha)
      }
    }

    records[[j]] <- do.call(rbind, lapply(designs, function(design) {
      data.frame(T = n, specification = design, method = methods,
                 reject = as.numeric(colMeans(rej[, design, ], na.rm = TRUE)),
                 Nsim = Nsim,
                 test = "No Granger causality from x to y",
                 stringsAsFactors = FALSE)
    }))
  }
  do.call(rbind, records)
}

granger_sample_sizes <- c(100, 250, 500, 1000, 2000)
set.seed(seeds[["granger"]])
granger_res <- simulate_granger(granger_sample_sizes, Nsim_gr, alpha)
granger_res$mcse <- mcse(granger_res$reject, granger_res$Nsim)

# =============================================================================
# 8. Extension 4: local power and size-adjusted critical values
#
# Under the local alternative  y_t = (b / sqrt(T)) x_t + v_t  with x and v
# independent AR(1) processes, we compare conventional and HAC tests using
# SIZE-ADJUSTED critical values (the empirical 95th percentile of |t| under
# b = 0).  Size adjustment is what makes the comparison meaningful: an
# oversized test always has more raw power, so raw power curves would simply
# restate the size distortion.
#
# The size-adjusted conventional critical value is itself informative.  By
# Proposition 3.5 the conventional t-ratio has an N(0, lambda) limit, so its
# 95th percentile should converge to 1.96 * sqrt(lambda) -- a sharper check on
# the proposition than any tail rejection probability.
# =============================================================================

simulate_local_power <- function(sample_sizes, b_grid, Nsim, alpha,
                                 phi_x = 0.8, phi_v = 0.8) {
  methods <- c("Conventional OLS", "HAC")
  power_records <- vector("list", length(sample_sizes))
  cv_records    <- vector("list", length(sample_sizes))

  for (j in seq_along(sample_sizes)) {
    n <- sample_sizes[j]
    tstat <- array(NA_real_, dim = c(Nsim, length(b_grid), length(methods)),
                   dimnames = list(NULL, as.character(b_grid), methods))

    for (bi in seq_along(b_grid)) {
      bloc <- b_grid[bi]
      for (r in seq_len(Nsim)) {
        x <- draw_ar1(n, phi_x)
        v <- draw_ar1(n, phi_v)
        y <- (bloc / sqrt(n)) * x + v
        tstat[r, bi, ] <- slope_t_stats(x, y)[methods]
      }
    }

    null_index <- which(b_grid == 0)
    cv <- vapply(methods, function(m)
      unname(quantile(abs(tstat[, null_index, m]), 1 - alpha)), numeric(1))

    # Jarque-Bera test of normality on the null (b = 0) t-statistics: the
    # critical-value comparison above checks the SCALE of the limit
    # distribution (whether lambda is estimated correctly); this checks its
    # SHAPE, i.e. whether the limit is normal at all, as Proposition
    # \ref{prop:tstat} also claims.
    jb <- vapply(methods, function(m)
      jarque_bera(tstat[, null_index, m]), numeric(2))

    cv_records[[j]] <- data.frame(
      T = n, method = methods, critical_value = cv,
      nominal = qnorm(1 - alpha / 2),
      implied_sqrt_lambda = cv / qnorm(1 - alpha / 2),
      jb_statistic = jb["statistic", ],
      jb_pvalue    = jb["p_value", ],
      Nsim = Nsim, stringsAsFactors = FALSE
    )

    power_records[[j]] <- do.call(rbind, lapply(seq_along(b_grid), function(bi) {
      data.frame(
        T = n, b = b_grid[bi], method = methods,
        power = vapply(methods, function(m)
          mean(abs(tstat[, bi, m]) > cv[[m]]), numeric(1)),
        Nsim = Nsim, stringsAsFactors = FALSE
      )
    }))
  }

  list(power = do.call(rbind, power_records),
       critical_values = do.call(rbind, cv_records))
}

power_sample_sizes <- c(250, 1000)
power_b_grid       <- c(0, 1, 2, 3, 4, 6, 8)
power_phi          <- 0.8
power_lambda       <- lambda_ar_pair(power_phi, power_phi)

set.seed(seeds[["power"]])
power_out <- simulate_local_power(power_sample_sizes, power_b_grid,
                                  Nsim_pow, alpha,
                                  phi_x = power_phi, phi_v = power_phi)
power_res    <- power_out$power
power_cv_res <- power_out$critical_values
power_res$mcse <- mcse(power_res$power, power_res$Nsim)
power_cv_res$theoretical <- qnorm(1 - alpha / 2) *
  ifelse(power_cv_res$method == "Conventional OLS", sqrt(power_lambda), 1)

# =============================================================================
# 9. Accessors used by the handout
#
# The handout quotes no hard-coded numbers: every figure in the prose is pulled
# from these accessors at render time.  Each one fails loudly rather than
# returning a wrong or empty value, so a mismatch between the text and the
# simulation cannot pass silently.
# =============================================================================

.one <- function(v, what) {
  v <- v[!is.na(v)]
  if (length(v) != 1L)
    stop(sprintf("accessor '%s' matched %d records, expected 1", what, length(v)))
  v
}

pc <- function(p, digits = 1) sprintf(paste0("%.", digits, "f%%"), 100 * p)

# main experiment
rej_of <- function(dgp_name, n, method = "Conventional OLS") {
  src <- if (identical(method, "HAC")) hac_res else res
  .one(src$reject[as.character(src$dgp) == dgp_name & src$T == n],
       sprintf("rej_of(%s, %d, %s)", dgp_name, n, method))
}
rp <- function(dgp_name, n, method = "Conventional OLS", digits = 1)
  pc(rej_of(dgp_name, n, method), digits)

dgp_jb <- function(dgp_name, n, method = "Conventional OLS",
                   what = c("jb_statistic", "jb_pvalue"), digits = 2) {
  what <- match.arg(what)
  sprintf(paste0("%.", digits, "f"),
          .one(dgp_normality_res[[what]][as.character(dgp_normality_res$dgp) == dgp_name &
                                         dgp_normality_res$T == n &
                                         dgp_normality_res$method == method],
               sprintf("dgp_jb(%s, %d, %s, %s)", dgp_name, n, method, what)))
}

lambda_of <- function(dgp_name)
  .one(dgp_spec$lambda[dgp_spec$dgp == dgp_name], sprintf("lambda_of(%s)", dgp_name))
asy_of <- function(dgp_name, digits = 1)
  pc(.one(dgp_spec$asymptotic[dgp_spec$dgp == dgp_name],
          sprintf("asy_of(%s)", dgp_name)), digits)

# extensions
cv_rej <- function(method, n, digits = 1)
  pc(.one(common_volatility_res$reject[common_volatility_res$method == method &
                                       common_volatility_res$T == n],
          sprintf("cv_rej(%s, %d)", method, n)), digits)
l2u_rej <- function(method, n, digits = 1)
  pc(.one(local_to_unity_res$reject[local_to_unity_res$method == method &
                                    local_to_unity_res$T == n],
          sprintf("l2u_rej(%s, %d)", method, n)), digits)
gr_rej <- function(spec, method, n, digits = 1)
  pc(.one(granger_res$reject[granger_res$specification == spec &
                             granger_res$method == method & granger_res$T == n],
          sprintf("gr_rej(%s, %s, %d)", spec, method, n)), digits)
pw <- function(method, n, bloc, digits = 1)
  pc(.one(power_res$power[power_res$method == method & power_res$T == n &
                          power_res$b == bloc],
          sprintf("pw(%s, %d, %g)", method, n, bloc)), digits)
pw_cv <- function(method, n, digits = 2)
  sprintf(paste0("%.", digits, "f"),
          .one(power_cv_res$critical_value[power_cv_res$method == method &
                                           power_cv_res$T == n],
               sprintf("pw_cv(%s, %d)", method, n)))
pw_jb <- function(method, n, what = c("jb_statistic", "jb_pvalue"), digits = 2) {
  what <- match.arg(what)
  sprintf(paste0("%.", digits, "f"),
          .one(power_cv_res[[what]][power_cv_res$method == method &
                                    power_cv_res$T == n],
               sprintf("pw_jb(%s, %d, %s)", method, n, what)))
}

# maximum Monte Carlo standard error of a proportion at a given N
max_mcse <- function(N, digits = 2) sprintf(paste0("%.", digits, "f"), 100 * sqrt(0.25 / N))

# =============================================================================
# 10. Figures
# =============================================================================

palette <- c(
  `iid` = "#7F7F7F", `(0.5,0.5)` = "#4477AA", `(0.8,0.8)` = "#EE6677",
  `(0.9,0.9)` = "#228833", `(0.95,0.95)` = "#CCBB44",
  `(0.9,0.5)` = "#66CCEE", `(0.8,-0.8)` = "#882255",
  `AR/MA lambda=1` = "#000000", `I(1)` = "#AA3377"
)

# A log x-axis is used throughout: on a linear axis the interval 2000-5000,
# where nothing happens, occupies most of the panel width.
log_T_scale <- function(breaks = selected_T)
  scale_x_log10(breaks = breaks, labels = breaks)

base_theme <- function(base_size = 9) {
  theme_classic(base_size = base_size) +
    theme(legend.position = "bottom",
          legend.box = "vertical",
          legend.margin = margin(t = 0, b = 0),
          plot.title = element_text(hjust = 0.5))
}

p1 <- ggplot(res, aes(T, reject, colour = dgp)) +
  geom_hline(yintercept = alpha, linetype = "dashed", linewidth = 0.45) +
  geom_line(linewidth = 0.55) +
  scale_colour_manual(values = palette) +
  scale_y_continuous(labels = percent_format(accuracy = 1),
                     breaks = seq(0, 1, 0.1)) +
  scale_x_log10(breaks = c(50, 100, 250, 500, 1000, 2500, 5000),
                labels = c(50, 100, 250, 500, 1000, 2500, 5000)) +
  coord_cartesian(ylim = c(0, 1)) +
  base_theme(10) +
  guides(colour = guide_legend(nrow = 3)) +
  labs(x = "Sample size T (log scale)",
       y = "Rejection frequency at the 5% level",
       colour = "DGP", title = "Conventional OLS inference")

hac_plot_data <- rbind(
  subset(res,     T %in% selected_T & dgp != "I(1)",
         select = c(T, reject, method, dgp)),
  subset(hac_res, dgp != "I(1)", select = c(T, reject, method, dgp))
)
p2 <- ggplot(hac_plot_data, aes(T, reject, colour = dgp, linetype = method,
                                shape = method)) +
  geom_hline(yintercept = alpha, linetype = "dotted", linewidth = 0.4) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1.3) +
  scale_colour_manual(values = palette) +
  scale_y_continuous(labels = percent_format(accuracy = 1),
                     breaks = seq(0, 0.7, 0.1)) +
  log_T_scale() +
  coord_cartesian(ylim = c(0, 0.72)) +
  base_theme() +
  guides(colour = guide_legend(nrow = 3, order = 1),
         linetype = guide_legend(nrow = 2, order = 2),
         shape = guide_legend(nrow = 2, order = 2)) +
  labs(x = "Sample size T (log scale)",
       y = "Rejection frequency at the 5% level",
       colour = "DGP", linetype = "Standard error", shape = "Standard error",
       title = "Conventional and HAC inference")

p3 <- ggplot(common_volatility_res, aes(T, reject, colour = method,
                                        linetype = method, shape = method)) +
  geom_hline(yintercept = alpha, linetype = "dotted") +
  geom_line(linewidth = 0.6) +
  geom_point(size = 1.5) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  log_T_scale() +
  expand_limits(y = 0) +
  base_theme() +
  labs(x = "Sample size T (log scale)", y = "Rejection frequency",
       colour = "Standard error", linetype = "Standard error",
       shape = "Standard error",
       title = "Dependent zero-projection series with common volatility")

p4 <- ggplot(local_to_unity_res, aes(T, reject, colour = method,
                                     linetype = method, shape = method)) +
  geom_hline(yintercept = alpha, linetype = "dotted") +
  geom_line(linewidth = 0.6) +
  geom_point(size = 1.5) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  log_T_scale() +
  coord_cartesian(ylim = c(0, 1)) +
  base_theme() +
  labs(x = "Sample size T (log scale)", y = "Rejection frequency",
       colour = "Standard error", linetype = "Standard error",
       shape = "Standard error",
       title = "Local-to-unity stationary sequences")

p5 <- ggplot(granger_res, aes(T, reject, colour = method,
                              linetype = method, shape = method)) +
  geom_hline(yintercept = alpha, linetype = "dotted") +
  geom_line(linewidth = 0.6) +
  geom_point(size = 1.5) +
  facet_wrap(~ specification) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_log10(breaks = granger_sample_sizes, labels = granger_sample_sizes) +
  expand_limits(y = 0) +
  base_theme() +
  labs(x = "Sample size T (log scale)", y = "Joint rejection frequency",
       colour = "Covariance", linetype = "Covariance", shape = "Covariance")

power_res$panel <- factor(paste0("T = ", power_res$T),
                          levels = paste0("T = ", power_sample_sizes))
p6 <- ggplot(power_res, aes(b, power, colour = method, linetype = method,
                            shape = method)) +
  geom_hline(yintercept = alpha, linetype = "dotted") +
  geom_line(linewidth = 0.6) +
  geom_point(size = 1.5) +
  facet_wrap(~ panel) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = power_b_grid) +
  coord_cartesian(ylim = c(0, 1)) +
  base_theme() +
  labs(x = "Local alternative index b   (slope = b / sqrt(T))",
       y = "Size-adjusted power",
       colour = "Standard error", linetype = "Standard error",
       shape = "Standard error",
       title = "Size-adjusted local power, AR(1) pair with phi = 0.8")

# =============================================================================
# 11. Outputs
# =============================================================================

output_dir <- Sys.getenv("SPURIOUS_OUTPUT_DIR", unset = "scripts")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

figures <- list(
  spurious_rejection_frequency      = list(plot = p1, w = 6.0, h = 4.4),
  spurious_hac_comparison           = list(plot = p2, w = 6.0, h = 4.6),
  spurious_common_volatility        = list(plot = p3, w = 5.6, h = 3.8),
  spurious_local_to_unity           = list(plot = p4, w = 5.6, h = 3.8),
  spurious_granger_misspecification = list(plot = p5, w = 6.0, h = 3.8),
  spurious_local_power              = list(plot = p6, w = 6.0, h = 3.8)
)
for (nm in names(figures)) {
  f <- figures[[nm]]
  ggsave(file.path(output_dir, paste0(nm, ".pdf")), f$plot,
         width = f$w, height = f$h)
}

tables <- list(
  spurious_rejection_frequency_series     = res,
  spurious_hac_rejection_frequency_series = hac_res,
  spurious_comparison_table               = comparison_table,
  spurious_hac_comparison_table           = hac_comparison_table,
  spurious_dgp_normality                  = dgp_normality_res,
  spurious_common_volatility              = common_volatility_res,
  spurious_local_to_unity                 = local_to_unity_res,
  spurious_granger_misspecification       = granger_res,
  spurious_local_power                    = power_res,
  spurious_local_power_critical_values    = power_cv_res
)
for (nm in names(tables)) {
  write.csv(tables[[nm]], file.path(output_dir, paste0(nm, ".csv")),
            row.names = FALSE)
}

writeLines(capture.output(sessionInfo()),
           file.path(output_dir, "sessionInfo.txt"))

# Note: the plot objects p1-p6 are returned to the caller for the handout to
# render.  Nothing is print()ed here, so sourcing this script never leaves a
# stray Rplots.pdf behind.
message("Simulation complete. Figures and CSV files written to ", output_dir)
